-- ============================================
-- SCHEMA COMPLETO - PROJETO PAGAMENTOS
-- Banco de Dados: PostgreSQL 14+
-- Padrão: MAIÚSCULO, snake_case
-- ============================================

-- Tabela: USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO BIGSERIAL NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,

    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO)
);

CREATE INDEX IDX_USUARIOS_USERNAME ON USUARIOS(USERNAME);

-- Tabela: EMPRESAS
CREATE TABLE EMPRESAS (
    ID_EMPRESA BIGSERIAL NOT NULL,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(18) NOT NULL UNIQUE,
    RAZAO VARCHAR(150),

    CONSTRAINT PK_EMPRESAS PRIMARY KEY (ID_EMPRESA),
    CONSTRAINT FK_EMPRESAS_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_EMPRESAS_USUARIO_CRIADOR ON EMPRESAS(ID_USUARIO_CRIADOR);
CREATE INDEX IDX_EMPRESAS_CNPJ ON EMPRESAS(CNPJ);

-- Tabela: PRESTADORES
CREATE TABLE PRESTADORES (
    COD_PRESTADOR BIGSERIAL NOT NULL,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,

    CONSTRAINT PK_PRESTADORES PRIMARY KEY (COD_PRESTADOR),
    CONSTRAINT FK_PRESTADORES_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_PRESTADORES_USUARIO_CRIADOR ON PRESTADORES(ID_USUARIO_CRIADOR);
CREATE INDEX IDX_PRESTADORES_CPF ON PRESTADORES(CPF);

-- Tabela: DADOS_BANCARIOS_PRESTADOR
CREATE TABLE DADOS_BANCARIOS_PRESTADOR (
    ID_DADOS_BANCARIO BIGSERIAL NOT NULL,
    COD_PRESTADOR BIGINT NOT NULL UNIQUE,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    BANCO VARCHAR(50),
    TIPO_CONTA VARCHAR(20),
    AGENCIA VARCHAR(10),
    CONTA VARCHAR(20),
    CHAVE_PIX VARCHAR(100),

    CONSTRAINT PK_DADOS_BANCARIOS PRIMARY KEY (ID_DADOS_BANCARIO),
    CONSTRAINT FK_DADOS_BANCARIOS_PRESTADOR FOREIGN KEY (COD_PRESTADOR)
        REFERENCES PRESTADORES(COD_PRESTADOR),
    CONSTRAINT FK_DADOS_BANCARIOS_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_DADOS_BANCARIOS_PRESTADOR ON DADOS_BANCARIOS_PRESTADOR(COD_PRESTADOR);
CREATE INDEX IDX_DADOS_BANCARIOS_USUARIO_CRIADOR ON DADOS_BANCARIOS_PRESTADOR(ID_USUARIO_CRIADOR);

-- Tabela: ENDERECOS
CREATE TABLE ENDERECOS (
    ID_ENDERECO BIGSERIAL NOT NULL,
    ID_EMPRESA BIGINT,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL,

    CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID_ENDERECO),
    CONSTRAINT FK_ENDERECOS_EMPRESA FOREIGN KEY (ID_EMPRESA)
        REFERENCES EMPRESAS(ID_EMPRESA),
    CONSTRAINT FK_ENDERECOS_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_ENDERECOS_EMPRESA ON ENDERECOS(ID_EMPRESA);
CREATE INDEX IDX_ENDERECOS_USUARIO_CRIADOR ON ENDERECOS(ID_USUARIO_CRIADOR);
CREATE INDEX IDX_ENDERECOS_CEP ON ENDERECOS(CEP);

-- Tabela: GRUPO_ITENS
CREATE TABLE GRUPO_ITENS (
    ID_GRUPO BIGSERIAL NOT NULL,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,

    CONSTRAINT PK_GRUPO_ITENS PRIMARY KEY (ID_GRUPO),
    CONSTRAINT FK_GRUPO_ITENS_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_GRUPO_ITENS_USUARIO_CRIADOR ON GRUPO_ITENS(ID_USUARIO_CRIADOR);

-- Tabela: ITENS
CREATE TABLE ITENS (
    ID_ITEM BIGSERIAL NOT NULL,
    ID_GRUPO BIGINT NOT NULL,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    VALOR_UNITARIO NUMERIC(10, 2),
    PRECO_MEDIO NUMERIC(10, 2),
    TIPO_UNITARIO VARCHAR(20),

    CONSTRAINT PK_ITENS PRIMARY KEY (ID_ITEM),
    CONSTRAINT FK_ITENS_GRUPO FOREIGN KEY (ID_GRUPO)
        REFERENCES GRUPO_ITENS(ID_GRUPO),
    CONSTRAINT FK_ITENS_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_ITENS_GRUPO ON ITENS(ID_GRUPO);
CREATE INDEX IDX_ITENS_USUARIO_CRIADOR ON ITENS(ID_USUARIO_CRIADOR);

-- Tabela: DESCONTO_ITEM
CREATE TABLE DESCONTO_ITEM (
    ID_DESCONTO BIGSERIAL NOT NULL,
    ID_ITEM BIGINT NOT NULL,
    QUANTIDADE_MINIMA INTEGER NOT NULL,
    PERCENTUAL_DESCONTO NUMERIC(5, 2),
    VALOR_FINAL NUMERIC(10, 2),
    DESCRICAO TEXT,

    CONSTRAINT PK_DESCONTO_ITEM PRIMARY KEY (ID_DESCONTO),
    CONSTRAINT FK_DESCONTO_ITEM_ITEM FOREIGN KEY (ID_ITEM)
        REFERENCES ITENS(ID_ITEM)
);

CREATE INDEX IDX_DESCONTO_ITEM_ITEM ON DESCONTO_ITEM(ID_ITEM);

-- Tabela: ORCAMENTOS
CREATE TABLE ORCAMENTOS (
    ORCAMENTO_ID BIGSERIAL NOT NULL,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    ENTIDADE BIGINT NOT NULL,
    COD_PRESTADOR BIGINT NOT NULL,
    MOVIMENTO DATE NOT NULL,
    DESCRICAO TEXT,
    VALOR NUMERIC(12, 2),
    VALOR_TOTAL_ITENS NUMERIC(12, 2),
    DESCONTO NUMERIC(12, 2),
    VALOR_FINAL NUMERIC(12, 2),
    TIPO_PAGAMENTO VARCHAR(30),

    CONSTRAINT PK_ORCAMENTOS PRIMARY KEY (ORCAMENTO_ID),
    CONSTRAINT FK_ORCAMENTOS_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT FK_ORCAMENTOS_EMPRESA FOREIGN KEY (ENTIDADE)
        REFERENCES EMPRESAS(ID_EMPRESA),
    CONSTRAINT FK_ORCAMENTOS_PRESTADOR FOREIGN KEY (COD_PRESTADOR)
        REFERENCES PRESTADORES(COD_PRESTADOR)
);

CREATE INDEX IDX_ORCAMENTOS_USUARIO_CRIADOR ON ORCAMENTOS(ID_USUARIO_CRIADOR);
CREATE INDEX IDX_ORCAMENTOS_EMPRESA ON ORCAMENTOS(ENTIDADE);
CREATE INDEX IDX_ORCAMENTOS_PRESTADOR ON ORCAMENTOS(COD_PRESTADOR);
CREATE INDEX IDX_ORCAMENTOS_MOVIMENTO ON ORCAMENTOS(MOVIMENTO);

-- Tabela: ORCAMENTO_ITENS
CREATE TABLE ORCAMENTO_ITENS (
    ID_ORCAMENTO_ITEM BIGSERIAL NOT NULL,
    ORCAMENTO_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    VALOR_UNITARIO NUMERIC(10, 2) NOT NULL,
    VALOR_TOTAL NUMERIC(10, 2),

    CONSTRAINT PK_ORCAMENTO_ITENS PRIMARY KEY (ID_ORCAMENTO_ITEM),
    CONSTRAINT FK_ORCAMENTO_ITENS_ORCAMENTO FOREIGN KEY (ORCAMENTO_ID)
        REFERENCES ORCAMENTOS(ORCAMENTO_ID),
    CONSTRAINT FK_ORCAMENTO_ITENS_ITEM FOREIGN KEY (ITEM_ID)
        REFERENCES ITENS(ID_ITEM)
);

CREATE INDEX IDX_ORCAMENTO_ITENS_ORCAMENTO ON ORCAMENTO_ITENS(ORCAMENTO_ID);
CREATE INDEX IDX_ORCAMENTO_ITENS_ITEM ON ORCAMENTO_ITENS(ITEM_ID);

-- Tabela: ORCAMENTO_IMAGENS
CREATE TABLE ORCAMENTO_IMAGENS (
    ID_IMAGEM BIGSERIAL NOT NULL,
    ORCAMENTO_ID BIGINT NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    TIPO_ARQUIVO VARCHAR(50),
    TAMANHO_ARQUIVO BIGINT,
    CAMINHO_ARQUIVO VARCHAR(500) NOT NULL,
    DATA_UPLOAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT PK_ORCAMENTO_IMAGENS PRIMARY KEY (ID_IMAGEM),
    CONSTRAINT FK_ORCAMENTO_IMAGENS_ORCAMENTO FOREIGN KEY (ORCAMENTO_ID)
        REFERENCES ORCAMENTOS(ORCAMENTO_ID)
);

CREATE INDEX IDX_ORCAMENTO_IMAGENS_ORCAMENTO ON ORCAMENTO_IMAGENS(ORCAMENTO_ID);

-- Tabela: SOLICITACOES_APROVACAO
CREATE TABLE SOLICITACOES_APROVACAO (
    SOLICITACAO_APROVACAO_ID BIGSERIAL NOT NULL,
    ORCAMENTO_ID BIGINT NOT NULL UNIQUE,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    MOVIMENTO DATE,
    STATUS_SOLICITACAO VARCHAR(30) NOT NULL DEFAULT 'PENDENTE',

    CONSTRAINT PK_SOLICITACOES_APROVACAO PRIMARY KEY (SOLICITACAO_APROVACAO_ID),
    CONSTRAINT FK_SOLICITACOES_APROVACAO_ORCAMENTO FOREIGN KEY (ORCAMENTO_ID)
        REFERENCES ORCAMENTOS(ORCAMENTO_ID),
    CONSTRAINT FK_SOLICITACOES_APROVACAO_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_SOLICITACOES_APROVACAO_ORCAMENTO ON SOLICITACOES_APROVACAO(ORCAMENTO_ID);
CREATE INDEX IDX_SOLICITACOES_APROVACAO_USUARIO_CRIADOR ON SOLICITACOES_APROVACAO(ID_USUARIO_CRIADOR);
CREATE INDEX IDX_SOLICITACOES_APROVACAO_STATUS ON SOLICITACOES_APROVACAO(STATUS_SOLICITACAO);

-- Tabela: PAGAMENTOS
CREATE TABLE PAGAMENTOS (
    PAGAMENTO_ID BIGSERIAL NOT NULL,
    SOLICITACAO_APROVACAO_ID BIGINT NOT NULL,
    COD_PRESTADOR BIGINT NOT NULL,
    ID_DADOS_BANCARIO BIGINT NOT NULL,
    ID_USUARIO_CRIADOR BIGINT NOT NULL,
    MOVIMENTO DATE,

    CONSTRAINT PK_PAGAMENTOS PRIMARY KEY (PAGAMENTO_ID),
    CONSTRAINT FK_PAGAMENTOS_SOLICITACAO FOREIGN KEY (SOLICITACAO_APROVACAO_ID)
        REFERENCES SOLICITACOES_APROVACAO(SOLICITACAO_APROVACAO_ID),
    CONSTRAINT FK_PAGAMENTOS_PRESTADOR FOREIGN KEY (COD_PRESTADOR)
        REFERENCES PRESTADORES(COD_PRESTADOR),
    CONSTRAINT FK_PAGAMENTOS_DADOS_BANCARIOS FOREIGN KEY (ID_DADOS_BANCARIO)
        REFERENCES DADOS_BANCARIOS_PRESTADOR(ID_DADOS_BANCARIO),
    CONSTRAINT FK_PAGAMENTOS_USUARIO_CRIADOR FOREIGN KEY (ID_USUARIO_CRIADOR)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE INDEX IDX_PAGAMENTOS_SOLICITACAO ON PAGAMENTOS(SOLICITACAO_APROVACAO_ID);
CREATE INDEX IDX_PAGAMENTOS_PRESTADOR ON PAGAMENTOS(COD_PRESTADOR);
CREATE INDEX IDX_PAGAMENTOS_DADOS_BANCARIOS ON PAGAMENTOS(ID_DADOS_BANCARIO);
CREATE INDEX IDX_PAGAMENTOS_USUARIO_CRIADOR ON PAGAMENTOS(ID_USUARIO_CRIADOR);
CREATE INDEX IDX_PAGAMENTOS_MOVIMENTO ON PAGAMENTOS(MOVIMENTO);

-- ============================================
-- COMENTÁRIOS NAS TABELAS (OPCIONAL)
-- ============================================

COMMENT ON TABLE USUARIOS IS 'Usuários do sistema com diferentes roles';
COMMENT ON TABLE EMPRESAS IS 'Empresas clientes do sistema';
COMMENT ON TABLE PRESTADORES IS 'Prestadores de serviços cadastrados';
COMMENT ON TABLE DADOS_BANCARIOS_PRESTADOR IS 'Dados bancários dos prestadores para pagamento';
COMMENT ON TABLE ENDERECOS IS 'Endereços das empresas';
COMMENT ON TABLE GRUPO_ITENS IS 'Grupos de itens/serviços';
COMMENT ON TABLE ITENS IS 'Itens/serviços que compõem os orçamentos';
COMMENT ON TABLE DESCONTO_ITEM IS 'Tabela de descontos progressivos por quantidade';
COMMENT ON TABLE ORCAMENTOS IS 'Orçamentos gerados para empresas';
COMMENT ON TABLE ORCAMENTO_ITENS IS 'Itens que compõem cada orçamento';
COMMENT ON TABLE ORCAMENTO_IMAGENS IS 'Imagens anexadas aos orçamentos';
COMMENT ON TABLE SOLICITACOES_APROVACAO IS 'Solicitações de aprovação de orçamentos';
COMMENT ON TABLE PAGAMENTOS IS 'Pagamentos realizados após aprovação';

-- ============================================
-- FIM DO SCHEMA
-- ============================================
